// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_fF4YSg3cjZAG_AMaXwpADldAn7eAtbk',
    appId: '1:826009203423:web:54972bbc57c6b7fd102f6a',
    messagingSenderId: '826009203423',
    projectId: 'campus-hub-d5c4d',
    authDomain: 'campus-hub-d5c4d.firebaseapp.com',
    storageBucket: 'campus-hub-d5c4d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxPo1L7gYKERKwY0hDZQNYNaLobX3LWYg',
    appId: '1:826009203423:android:f85fe7436273e559102f6a',
    messagingSenderId: '826009203423',
    projectId: 'campus-hub-d5c4d',
    storageBucket: 'campus-hub-d5c4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB_ZJP1uuqgpBZmP0LpXwZSIdHPlCGg0E',
    appId: '1:826009203423:ios:b606c9c79da18140102f6a',
    messagingSenderId: '826009203423',
    projectId: 'campus-hub-d5c4d',
    storageBucket: 'campus-hub-d5c4d.firebasestorage.app',
    iosClientId: '826009203423-c6ri10epacq37vel7lbl9m3m8cl79hds.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB_ZJP1uuqgpBZmP0LpXwZSIdHPlCGg0E',
    appId: '1:826009203423:ios:b606c9c79da18140102f6a',
    messagingSenderId: '826009203423',
    projectId: 'campus-hub-d5c4d',
    storageBucket: 'campus-hub-d5c4d.firebasestorage.app',
    iosClientId: '826009203423-c6ri10epacq37vel7lbl9m3m8cl79hds.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_fF4YSg3cjZAG_AMaXwpADldAn7eAtbk',
    appId: '1:826009203423:web:7d984a1c4e647d67102f6a',
    messagingSenderId: '826009203423',
    projectId: 'campus-hub-d5c4d',
    authDomain: 'campus-hub-d5c4d.firebaseapp.com',
    storageBucket: 'campus-hub-d5c4d.firebasestorage.app',
  );
}
